services:
  - type: web
    name: pdf-shuffler
    env: python
    plan: free
    buildCommand: "apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-heb tesseract-ocr-eng tesseract-ocr-ara poppler-utils libgl1-mesa-glx libglib2.0-0 && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --config gunicorn.conf.py"
    envVars:
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: TESSDATA_PREFIX
        value: "/usr/share/tesseract-ocr/4.00/tessdata/"

